---
galaxy_info:
  author: JGoutin
  description: "This Ansible role installs a standalone music player on Fedora
                (Lollypop by default)."
  license: GPL-3.0
  min_ansible_version: 2.10
  platforms:
    - name: Fedora
      versions:
        - 32
        - 33
  galaxy_tags:
    - fedora
    - system
    - lollypop
    - music
    - kiosk

dependencies: []
